version: "3"
services:

  mssql-server:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Ids_mari2021"
      ACCEPT_EULA: "Y"